### ISSUE TITLE
Lint error in LowercaseObjectKeys.d.t

### ISSUE THREAD

**Issue by cfficaurzua** [octet-stream/form-data-encoder#8] opened 2022-08-10 21:24 UTC
Hi, I got a lint error in the types definition. 
```
./node_modules/form-data-encoder/@type/util/LowercaseObjectKeys.d.ts:3:19 - error TS1005: ']' expected.

3     [K in keyof T as K extends string ? Lowercase<K> : K]: T[K];
                    ~~

../node_modules/form-data-encoder/@type/util/LowercaseObjectKeys.d.ts:3:22 - error TS1005: ';' expected.

3     [K in keyof T as K extends string ? Lowercase<K> : K]: T[K];
                       ~

../node_modules/form-data-encoder/@type/util/LowercaseObjectKeys.d.ts:3:24 - error TS1005: ';' expected.

3     [K in keyof T as K extends string ? Lowercase<K> : K]: T[K];
                         ~~~~~~~

../node_modules/form-data-encoder/@type/util/LowercaseObjectKeys.d.ts:3:54 - error TS1005: '(' expected.

3     [K in keyof T as K extends string ? Lowercase<K> : K]: T[K];
                                                       ~

../node_modules/form-data-encoder/@type/util/LowercaseObjectKeys.d.ts:3:57 - error TS1005: ',' expected.

3     [K in keyof T as K extends string ? Lowercase<K> : K]: T[K];
                                                          ~

../node_modules/form-data-encoder/@type/util/LowercaseObjectKeys.d.ts:3:58 - error TS1135: Argument expression expected.

3     [K in keyof T as K extends string ? Lowercase<K> : K]: T[K];
                                                           ~

../node_modules/form-data-encoder/@type/util/LowercaseObjectKeys.d.ts:3:64 - error TS1005: ')' expected.

3     [K in keyof T as K extends string ? Lowercase<K> : K]: T[K];
                                                                 ~

../node_modules/form-data-encoder/@type/util/LowercaseObjectKeys.d.ts:4:1 - error TS1128: Declaration or statement expected.

4 };
  ~


Found 8 errors.
```

tsc version = Version 4.7.4

**Comment by octet-stream** [comment] 2022-09-04 16:06
Hi. Sorry for the late response. How can I reproduce the issue?

**Comment by FrankyFrankFrank** [comment] 2022-10-03 14:45
@cfficaurzua What version of Typescript are you using? This package uses `4.8.4`.  When we updated from `3.*` we were able to get over the issue.

**Comment by octet-stream** [comment] 2022-10-03 18:34
> What version of Typescript are you using?

The original post mentions version 4.7.4.
I already decided to remove this helper and write necessary types myself instead. This change will be released soon.

**Comment by octet-stream** [comment] 2022-10-03 18:37
I've also tested tsc compilation in v4.3.x:
```sh
npm exec --package=typescript@4.3 -- tsc --noEmit
```

so that would likely be the minimum required version, because it was the one introducing support for private methods from the ECMAScript spec.

**Comment by octet-stream** [comment] 2022-10-03 20:49
Try https://github.com/octet-stream/form-data-encoder/releases/tag/v2.1.3. I hope the issue is resolved.

**Comment by octet-stream** [comment] 2022-11-18 01:06
I am closing this as completed. Feel free to reopen if the issue is still remains in the latest version.

**Closed by octet-stream** 2022-11-18 01:06 UTC
Labels: bug
